INSERT INTO CURRENCY_VALUE  (ID ,CURRENCY_MULTIPLIER ,CURRENCY_FROM ,CURRENCY_TO ) VALUES (1,12000,'btc','usd');
INSERT INTO CURRENCY_VALUE  (ID ,CURRENCY_MULTIPLIER ,CURRENCY_FROM ,CURRENCY_TO ) VALUES (2,4000,'eth','usd');
INSERT INTO CURRENCY_VALUE  (ID ,CURRENCY_MULTIPLIER ,CURRENCY_FROM ,CURRENCY_TO ) VALUES (3,73,'usd','inr');
INSERT INTO CURRENCY_VALUE  (ID ,CURRENCY_MULTIPLIER ,CURRENCY_FROM ,CURRENCY_TO ) VALUES (4,290000,'usd','rial');